QRS-27, create users tab
Nospoko/data-quality-platform pull request #16
Opened 2023-08-08 10:25 UTC by VitalInnovator

added user tab to admin page

2023-08-08 14:42 UTC, roszcz commented
@VitalInnovator thanks! Can you add some documentation in the readme about the user/orgranization/dataset management? Some kind of  a basic example about how to deal with the dataset access will be enough in the end

2023-08-09 18:10 UTC, roszcz commented
@VitalInnovator Can you please make the documentation a priority? Everything looks great, but I'm not able to see any data without additional information on how to set up the dataset access.

<img width="420" alt="image" src="https://github.com/Nospoko/data-quality-platform/assets/8056825/188a59cd-47cb-4de4-a834-ded6d643dd20">

2023-08-13 10:17 UTC, roszcz commented
@VitalInnovator can you make instructions to actually get to a stage where I see signals on a dashboard explicit, please? I'm still unable to test this PR due to the lacking documentation.

2023-08-14 16:56 UTC, roszcz requested changes
Thanks!

I have a couple change requests:

- [x] Change `datasetName` to `dataset_name` parameter name in the `/data` call
- [x] Change `datasetNames` to `dataset_names` in the `/datasets` call
- [x] In the Dataset Access table, when users click "Add Dataset Access", show all active and inactive datasets (now it shows only active)
- [x] Looks like deactivating and activating a dataset removes access? Access shouldn't go away when dataset is deactivated. (see video)
- [ ] Show inactive datasets on the dashboard, add a note "Dataset inactive, concat admin to activate"

I left more directly on the code.

https://github.com/Nospoko/data-quality-platform/assets/8056825/1e3a9809-0440-493b-b1d1-829f7b4faa1b

2023-08-14 16:56 UTC, roszcz commented on next/src/modules/adminPage/components/SubTable.tsx
> +              ? 'Add New Dataset'
```suggestion
              ? 'Add Dataset Access'
```

I think this is more accurate

2023-08-14 16:56 UTC, roszcz commented on README.md
> +5. Use pgAdmin or another similar tool, and in the 'users' table, set the value of the 'role' field to 'admin'.
```suggestion
5. Use pgAdmin or another similar tool, and in the 'users' table, set the value of the 'role' field to 'admin'. Raw query: `UPDATE users SET role='admin'::users_role_enum WHERE email='user@email.com';`
```

2023-08-14 17:00 UTC, roszcz commented
@VitalInnovator you can add an unused parameter in the python API in this PR:

```py
async def get_record(exam_uid: str, position: int, dataset_name: str):
  ...
```

And don't worry about the `/datasets` endpoint for now. When we close this, I'll work on the dataset sync and add this endpoint.

2023-08-15 05:07 UTC, VitalInnovator commented
@roszcz I've implemented your feedback

2023-08-15 13:08 UTC, roszcz commented
Here's some more cosmetic changes:

- [ ] If the user is logged in, point them to the dashboard, not to the guide.
- [ ] In the datasets tab, change the buttons text from "Change State" to either "Activate" or "Deactivate", depending on the current dataset status.
- [ ] In the request to `/datasets`, include the information about expected state, payload could look like this:
```json
{
  "datasets": [
    { "dataset_name": "foo", "state": "active" },
    { "dataset_name": "bar", "state": "inactive"},
  ]
}
```

2023-08-16 12:58 UTC, roszcz approved these changes

2023-08-16 13:00 UTC, merged